ELM_MAKE=elm make

OUTDIR=PremaidCommander
SRCDIR=src
ETCDIR=etc

ELMMAIN=Main
MANIFEST=manifest.json
BACKGROUNDJS=background.js
ELMIMPORTJS=elm_import.js
INDEXHTML=index.html

PKGFILES=$(OUTDIR)/$(ELMMAIN).js $(OUTDIR)/$(MANIFEST) $(OUTDIR)/$(BACKGROUNDJS) $(OUTDIR)/$(INDEXHTML) $(OUTDIR)/$(ELMIMPORTJS)

all: $(OUTDIR) $(PKGFILES)
	zip archive -r $(OUTDIR)

$(OUTDIR)/$(ELMMAIN).js : $(SRCDIR)/elm/$(ELMMAIN).elm
	$(ELM_MAKE) $(SRCDIR)/elm/$(ELMMAIN).elm --output=$(OUTDIR)/$(ELMMAIN).js

$(OUTDIR)/$(MANIFEST) : $(ETCDIR)/$(MANIFEST)
	cp $(ETCDIR)/$(MANIFEST) $(OUTDIR)/$(MANIFEST)

$(OUTDIR)/$(BACKGROUNDJS) : $(SRCDIR)/$(BACKGROUNDJS)
	cp $(SRCDIR)/$(BACKGROUNDJS) $(OUTDIR)/$(BACKGROUNDJS)

$(OUTDIR)/$(ELMIMPORTJS) : $(SRCDIR)/js/$(ELMIMPORTJS)
	cp $(SRCDIR)/js/$(ELMIMPORTJS) $(OUTDIR)/$(ELMIMPORTJS)

$(OUTDIR)/$(INDEXHTML) : $(SRCDIR)/$(INDEXHTML)
	cp $(SRCDIR)/$(INDEXHTML) $(OUTDIR)/$(INDEXHTML)


$(OUTDIR):
	mkdir $@
